repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff Lint
        entry: docker compose run --rm -T --entrypoint poetry ranking_ope run ruff
        language: system
        types: [python]
        args: [--config, /app/pyproject.toml]
        pass_filenames: true # staging files only
