dataset_name: "EUR-Lex4K" # EUR-Lex4K or "RCV1-2K"
n_val_seeds: 1000
dim_context: 10
reward_std: 3.0
max_reward_noise: 0.2
n_unique_action_at_k: 20
len_list: 5
n_cat_dim: 5
n_cat_per_dim: 5
random_state: 12345
beta: 1.0
eps: 0.1
val_size_list:
  - 1000
  - 2000
  - 4000
  - 8000
