n_val_seeds: 1000
val_size: 10000
n_test_seeds: 100
test_size: 10000
dim_context: 3
n_unobserved_cat_dim: 0
len_list: 7
beta: -1.0
eps: 0.3
reward_noise: 0.5
interaction_noise: 3.0
random_state: 12345
user_behavior:
  - "cascade"
  - "independent"
  - "standard"

defaults:
  - _self_
  - variation: len_list

hydra:
  run:
    dir: src/synthetic/logs/${hydra.job.name}/
